# -*- coding: utf-8 -*-
"""5DATA005C_20230798_Saarah_Badurdeen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ddq3FwcHFQhX1coJ2MjnMU9LD9hyAqk8
"""

#Mount google drive to collab
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

casualty = pd.read_csv('/content/drive/MyDrive/Coursework/UK Road Safety/Casualty - last 5 years.csv')
collision = pd.read_csv('/content/drive/MyDrive/Coursework/UK Road Safety/Collision - last 5 years.csv')
vehicle = pd.read_csv('/content/drive/MyDrive/Coursework/UK Road Safety/Vehicle - last 5 years.csv')

#Dimension of data (i.e., total number of data points & attributes)

#Dimension of data for the Casualty dataset
print('Casualty DataFrame:')
print('Shape:', casualty.shape)
print('Number of data points:', casualty.shape[0])
print('Number of attributes:', casualty.shape[1])

#Dimension of data for the Collision dataset
print('Collision DataFrame:')
print('Shape:', collision.shape)
print('Number of data points:', collision.shape[0])
print('Number of attributes:', collision.shape[1])

#Dimension of data for the Vehicle dataset
print('Vehicle DataFrame:')
print('Shape:', vehicle.shape)
print('Number of data points:', vehicle.shape[0])
print('Number of attributes:', vehicle.shape[1])

#Attributes data types
print('Casualty DataFrame:')
print(casualty.dtypes)

#Attributes data types
print('Collision DataFrame:')
print(collision.dtypes)

#Attributes data types
print('Vehicle DataFrame:')
print(vehicle.dtypes)

#Number & percentage of missing values for each attribute
print('Casualty DataFrame:')
print(casualty.isnull().sum())
print('Missing percentage of casualty')
missing_percentage_casualty = (casualty.isnull().sum() / len(casualty)) * 100
print(missing_percentage_casualty[missing_percentage_casualty>0])

#Number & percentage of missing values for each attribute
print('Collision DataFrame:')
print(collision.isnull().sum())
print('Missing percentage of collision')
missing_percentage_collision = (collision.isnull().sum() / len(collision)) * 100
print(missing_percentage_collision[missing_percentage_collision>0])

#Number & percentage of missing values for each attribute
print('Vehicle DataFrame:')
print(vehicle.isnull().sum())
print('Missing percentage of vehicle')
missing_percentage_vehicle = (vehicle.isnull().sum() / len(vehicle)) * 100
print(missing_percentage_vehicle[missing_percentage_vehicle>0])

#Descriptive statistics for numeric attributes of Casualty dataframe
print('Casualty DataFrame - Descriptive statistics for numeric attributes:')
casualty.describe()

#Descriptive statistics for non-numeric attributes of Casualty dataframe
print('Casualty DataFrame - Descriptive statistics for non-numeric attributes:')
casualty.describe(include=['object'])

#Descriptive statistics for numeric attributes of Collision dataframe
print('Collision DataFrame - Descriptive statistics for numeric attributes:')
collision.describe()

#Descriptive statistics for non-numeric attributes of Collision dataframe
print('Collision DataFrame - Descriptive statistics for non-numeric attributes:')
collision.describe(include=['object'])

#Descriptive statistics for numeric attributes of Vehicle dataframe
print('Vehicle DataFrame - Descriptive statistics for numeric attributes:')
vehicle.describe()

#Descriptive statistics for non-numeric attributes of Collision dataframe
print('Vehicle DataFrame - Descriptive statistics for non-numeric attributes:')
vehicle.describe(include=['object'])

"""Age Distribution of Casualties by Severity



This KDE plot will show the distribution of casualty ages, separated by their severity level. This can highlight if specific age groups are more affected by certain severities.
"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(12, 7))
sns.kdeplot(data=casualty[(casualty['age_of_casualty'] != -1) & (casualty['casualty_severity'] != -1)],
            x='age_of_casualty', hue='casualty_severity', fill=True, palette={1: '#2A9D8F',  # Fatal - red
    2: '#F1C40F',  # Serious - yellow
    3: '#E63946'   # Slight - teal
}, common_norm=False)
plt.title('Age Distribution of Casualties by Severity (Excluding Unknowns)')
plt.xlabel('Age of Casualty')
plt.ylabel('Density')
plt.legend(title='Casualty Severity', labels=['Fatal (1)', 'Serious (2)', 'Slight (3)'])
plt.show()

"""### 5. Multiple Bar Chart of Casualty Severity vs. Casualty Class

This chart will display the count of casualties, segmented by their severity and further categorized by their class (e.g., driver, passenger, pedestrian). This can highlight which casualty classes are more affected by different severity levels.
"""

plt.figure(figsize=(10, 6))
# Filter out '-1' values from both 'casualty_severity' and 'casualty_class'
filtered_casualty = casualty[(casualty['casualty_severity'] != -1) & (casualty['casualty_class'] != -1)]

sns.countplot(data=filtered_casualty, x='casualty_severity', hue='casualty_class', palette='tab10')
plt.title('Casualty Severity vs. Casualty Class (Excluding Unknowns)')
plt.xlabel('Casualty Severity')
plt.ylabel('Number of Casualties')
plt.legend(title='Casualty Class', labels=['Driver/Rider (1)', 'Passenger (2)', 'Pedestrian (3)'])
plt.xticks(ticks=[0, 1, 2], labels=['Fatal (1)', 'Serious (2)', 'Slight (3)']) # Assuming severity 1,2,3 mapped to these categories
plt.tight_layout()
plt.show()

"""Trend of accidents per year/month"""

# Ensure 'date' column is in datetime format
# This is necessary if the 'date' column was previously reverted to string type.
if not pd.api.types.is_datetime64_any_dtype(collision['date']):
    collision['date'] = pd.to_datetime(collision['date'], format='%d/%m/%Y', errors='coerce')

# Calculate accidents per month using chained operations
accidents_per_month = (
    collision['date'].dt.to_period('M')  # Convert to monthly period
    .value_counts()  # Count occurrences for each period
    .sort_index()  # Sort by period (chronologically)
    .reset_index(name='number_of_accidents')  # Convert to DataFrame
)
# The column created by reset_index is named 'date' (from the Series name), not 'index'.
# Rename the 'date' column to 'year_month'.
accidents_per_month.rename(columns={'date': 'year_month'}, inplace=True)
# Convert 'year_month' to string for proper plotting on x-axis
accidents_per_month['year_month'] = accidents_per_month['year_month'].astype(str)

plt.figure(figsize=(14, 7))
sns.lineplot(data=accidents_per_month, x='year_month', y='number_of_accidents', marker='o')
plt.title('Trend of Accidents per Year/Month')
plt.xlabel('Year-Month')
plt.ylabel('Number of Accidents')
plt.xticks(rotation=90)
plt.grid(True)
plt.tight_layout()
plt.show()

"""### Heatmap of Accident Density by Latitude/Longitude

This heatmap visualizes the spatial distribution of accidents by using Kernel Density Estimation (KDE) based on the `latitude` and `longitude` coordinates from the `collision` dataset. Invalid coordinates (e.g., -1 or NaN) will be excluded for accurate representation.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Filter out invalid latitude and longitude values (e.g., -1 or NaN)
# Assuming -1 indicates unknown values, and .dropna() handles NaNs
filtered_collision_coords = collision[(collision['latitude'] != -1) &
                                      (collision['longitude'] != -1) &
                                      (collision['latitude'].notna()) &
                                      (collision['longitude'].notna())]

plt.figure(figsize=(12, 10))
sns.kdeplot(x=filtered_collision_coords['longitude'],
            y=filtered_collision_coords['latitude'],
            fill=True, cmap='viridis',
            cbar=True, cbar_kws={'label': 'Density of Accidents'})
plt.title('Heatmap of Accident Density by Latitude/Longitude')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.grid(False) # Turn off grid for better heatmap visualization
plt.tight_layout()
plt.show()

"""### Stacked Bar Chart of Vehicle Types vs. Accident Severity

This chart will display the distribution of vehicle types involved in accidents, broken down by the severity of the collision. To achieve this, we need to merge the `vehicle` and `collision` dataframes on a common key (`collision_index`) and then filter out unknown values in both `vehicle_type` and `collision_severity` before plotting.
"""

#Stacked bar chart of vehicle types vs. accident severity for the vehicle dataset
# Merge vehicle and collision dataframes on collision_index to get severity information
vehicle_collision = pd.merge(
    vehicle,
    collision[['collision_index', 'collision_severity']],
    on='collision_index',
    how='left'
)

# Filter out unknown/unspecified values (-1) from both columns
filtered_vehicle_collision = vehicle_collision[
    (vehicle_collision['vehicle_type'] != -1) &
    (vehicle_collision['collision_severity'] != -1)
]

# Create a cross-tabulation for counts
vehicle_severity_counts = pd.crosstab(
    filtered_vehicle_collision['vehicle_type'],
    filtered_vehicle_collision['collision_severity']
)

# Plotting the stacked bar chart
plt.figure(figsize=(15, 8))
vehicle_severity_counts.plot(kind='bar', stacked=True, colormap='viridis', figsize=(15, 8))

plt.title('Vehicle Type Distribution by Collision Severity')
plt.xlabel('Vehicle Type')
plt.ylabel('Number of Vehicles Involved')

# Map severity codes to labels for better readability
severity_labels = {1: 'Fatal', 2: 'Serious', 3: 'Slight'}
plt.legend(title='Collision Severity', labels=[severity_labels[col] for col in vehicle_severity_counts.columns])

plt.xticks(rotation=90)

plt.tight_layout()
plt.show()

"""### Correlation Matrix of Numerical Fields in the Vehicle Dataset

This correlation matrix will visualize the pairwise correlation coefficients between all numerical columns in the `vehicle` DataFrame. A heatmap is used to make it easy to identify strong positive or negative correlations.
"""

#Correlation matrix of numerical fields of vehicle dataset
plt.figure(figsize=(16, 12))
# Select only numeric columns for correlation
numeric_vehicle = vehicle.select_dtypes(include=['number'])
correlation_matrix = numeric_vehicle.corr()
sns.heatmap(correlation_matrix, annot=False, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix of Numerical Fields in Vehicle Dataset')
plt.tight_layout()
plt.show()

"""Data cleaning"""

#Check the redundant attributes in Casualty dataset
constant_columns = [col for col in casualty.columns if casualty[col].nunique() == 1]
print(constant_columns)

#Check the redundant attributes in Vehicle dataset
constant_columns = [col for col in vehicle.columns if vehicle[col].nunique() == 1]
print(constant_columns)

#Check the redundant attributes in Collision dataset
constant_columns = [col for col in collision.columns if collision[col].nunique() == 1]
print(constant_columns)

"""Investigate on the Outliers of the 03 datasets"""

#Investigate whether there are any outliers in the casualty dataset
numerical_features = casualty.select_dtypes(include=['int64', 'float64'])
print("Numerical features in Casualty DataFrame:")
print(numerical_features.columns)

# Calculate Q1 (25th percentile) and Q3 (75th percentile) for each numerical feature
Q1 = numerical_features.quantile(0.25)
Q3 = numerical_features.quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers_iqr = ((numerical_features < lower_bound) |
                (numerical_features > upper_bound)).sum()
print(f"{numerical_features}:{outliers_iqr}outliers_iqr")

#Investigate whether there are any outliers in the collision dataset
numerical_features = collision.select_dtypes(include=['int64', 'float64'])
print("Numerical features in Collision DataFrame:")
print(numerical_features.columns)

# Calculate Q1 (25th percentile) and Q3 (75th percentile) for each numerical feature
Q1 = numerical_features.quantile(0.25)
Q3 = numerical_features.quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers_iqr = ((numerical_features < lower_bound) |
                (numerical_features > upper_bound)).sum()
print(f"{numerical_features}:{outliers_iqr}outliers_iqr")

#Investigate whether there are any outliers in the Vehicle dataset
numerical_features = vehicle.select_dtypes(include=['int64', 'float64'])
print("Numerical features in Vehicle DataFrame:")
print(numerical_features.columns)

# Calculate Q1 (25th percentile) and Q3 (75th percentile) for each numerical feature
Q1 = numerical_features.quantile(0.25)
Q3 = numerical_features.quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers_iqr = ((numerical_features < lower_bound) |
                (numerical_features > upper_bound)).sum()
print(f"{numerical_features}:{outliers_iqr}outliers_iqr")

"""Proceed with the Data cleaning

Since there are no missing values as per the previous output generated from the Casualty dataset we shall proceed to proof check whether there are any negative and unknown values available in this dataset
"""

#Check for negative datapoints present in this dataset
numeric_cols = casualty.select_dtypes(include=['number'])
cols_with_neg_values = numeric_cols.columns[(numeric_cols < 0).any()]
print(f'cols_with_neg_values = ', list(cols_with_neg_values))

"""Since significant attributes such as sex of casualty & age of casualty cannot contain any negative or unknown values we shall check the count and decide whether these are to be dropped or not."""

casualty_neg_value = (numeric_cols < 0).sum()
print(f'Negative values in the numeric fields of the vehicle DataFrame:\n{casualty_neg_value}')

#Percentage of negative values in sex_of_casualty
percentage_of_sex_of_casualty = (casualty['sex_of_casualty'] <= 0 ).sum() / len(casualty)*100
print(f"Percentage of unidentified sex of casualty = {percentage_of_sex_of_casualty:.1f}%")

#Percentage of negative values in age_of_casualty
percentage_of_age_of_casualty = (casualty['age_of_casualty']<= 0 ).sum() / len(casualty)*100
print(f"Percentage of unidentified age of casualties = {percentage_of_age_of_casualty:.1f}%")

# Filter rows where 'sex_of_casualty' is negative
casualty = casualty[casualty['sex_of_casualty'] >= 0]

# Verify that negative values are no longer present
negative_sex_count = (casualty['sex_of_casualty'] <= 0).sum()
print(f"Number of negative 'sex_of_casualty' values after cleaning: {negative_sex_count}")

#Check the unique number of unknown values available
unknown_val_of_sex_of_casualty = casualty['sex_of_casualty'].unique()
print(f"unknown_val_of_sex_of_casualty = {unknown_val_of_sex_of_casualty}")

#Check the count of the unknown values
count_of_unknown_val_of_sex_of_casualty = (casualty['sex_of_casualty'] == 9).sum()
print(f"count_of_unknown_val_of_sex_of_casualty = {count_of_unknown_val_of_sex_of_casualty}")

#Drop these values since the count is extremely low
casualty_cleaned_sex = casualty[casualty['sex_of_casualty'] !=9]
print(f"Unique values in 'sex_of_casualty' after cleaning: {casualty_cleaned_sex['sex_of_casualty'].unique()}")

#Replace the negative values and zero values of age of casualty attribute with NaN
import numpy as np
casualty['age_of_casualty'] = casualty['age_of_casualty'].replace([-1], np.nan)
print(f'Min age: {casualty["age_of_casualty"].min()}')

# Calculate the median age, excluding NaN values
median_age = casualty['age_of_casualty'].median()

# Fill NaN values in 'age_of_casualty' with the median age
casualty['age_of_casualty'] = casualty['age_of_casualty'].fillna(median_age)

# Convert the 'age_of_casualty' column to int64
casualty['age_of_casualty'] = casualty['age_of_casualty'].astype(int)

# Verify the data type after conversion
print("Data type of 'age_of_casualty' after conversion:")
print(casualty['age_of_casualty'].dtypes)

"""Feature engineering for Casualty dataset

Encoding at least one categorical variable.
"""

# Get unique values and their counts for 'casualty_class'
casualty_class_counts = casualty['casualty_class'].value_counts().sort_index()
print("Casualty Class Unique Values and Counts:\n", casualty_class_counts)

# Step 1: Map numbers to meaningful names
casualty_class_map = {
    1: 'Driver',
    2: 'Passenger',
    3: 'Pedestrian'
}

# Apply mapping directly to the column
casualty['casualty_class'] = casualty['casualty_class'].astype(int).map(casualty_class_map)

# Step 2: One-hot encode (This comment seems to indicate a further step, which is not in this cell)
print(f'casualty_class = ',casualty['casualty_class'].unique())

"""Generate a new attribute for the casualty dataset"""

def categorize_age(age):
    if pd.isnull(age):
        return 'Unknown'
    elif age < 18:
        return 'Child'
    elif age < 65:
        return 'Adult'
    else:
        return 'Senior'

casualty['Casualty_Age_Group'] = casualty['age_of_casualty'].apply(categorize_age)

# Display the new attribute by showing its value counts
print(casualty['Casualty_Age_Group'].value_counts())
print(casualty.dtypes)

"""Data cleaning - Collision Dataset"""

print('Collision DataFrame:')
print(collision.dtypes)

"""We can see that there are same versions of historical & current attributes. We shall proceed to drop them."""

#Removing attributes which are historic as the current attributes are present.
dropping_col = ["local_authority_highway", "junction_detail_historic", "pedestrian_crossing_human_control_historic", "pedestrian_crossing_physical_facilities_historic", "carriageway_hazards_historic"]
collision = collision.drop(columns=dropping_col,errors = 'ignore')
print('Collision cleaned DataFrame:')
print(collision.dtypes)

"""The below coding was carried out with the help of Gemini as the structure and data types of the collision was changed due to the trendline we generated previously."""

# Convert 'date' back to its original string/object format
# Assuming the original string format was '%d/%m/%Y'
# This check handles if 'date' is currently datetime or Period object
if pd.api.types.is_datetime64_any_dtype(collision['date']):
    collision['date'] = collision['date'].dt.strftime('%d/%m/%Y')
elif pd.api.types.is_period_dtype(collision['date']):
    collision['date'] = collision['date'].dt.to_timestamp().dt.strftime('%d/%m/%Y')

# Drop the 'year_month' column if it exists
if 'year_month' in collision.columns:
    collision = collision.drop(columns=['year_month'])

print('Collision DataFrame after reverting data types for date and removing year_month:')
print(collision.dtypes)

"""Feature Engineering - Collision Dataset"""

#Imputing values for attributes with missing data
collision['location_easting_osgr'] = collision['location_easting_osgr'].fillna(collision['location_easting_osgr'].median())
collision['location_northing_osgr'] = collision['location_northing_osgr'].fillna(collision['location_northing_osgr'].median())
collision['longitude'] = collision['longitude'].fillna(collision['longitude'].median())
collision['latitude'] = collision['latitude'].fillna(collision['latitude'].median())
collision['local_authority_highway_current'] = collision['local_authority_highway_current'].fillna(collision['local_authority_highway_current'].mode()[0])

#Proof check whether there any missing values still
#Analyze the attributes with missing values
missing_values = collision.isnull().sum()
print(missing_values)

#To check attributes with negative values
numeric_cols = collision.select_dtypes(include=['number'])
cols_with_neg_values = numeric_cols.columns[(numeric_cols < 0).any()]
print(f'cols_with_neg_values = {(cols_with_neg_values)}')

#Since speed limit is not practical to be negative we shall check the number of negaative values present and try to drop them.
negative_speed_limit = (collision['speed_limit'] < 0).sum()
print(f'negative_speed_limit = {(negative_speed_limit)}')

#Proceed to drop the negative values of speed limit
new_speed_limit = collision[collision['speed_limit'] >= 0]

#Now proof check whether any negative values are present in speed limit attribute
new_speed_limit = (new_speed_limit['speed_limit'] < 0).sum()
print(f'new_speed_limit = {(new_speed_limit)}')

"""Encoding weather conditions"""

#Encoding weather conditions
import numpy as np
weather_conditions = collision['weather_conditions'].unique()
print(f'weather_conditions = {np.sort(weather_conditions)}')

#Start the weather encoding
weather_map = {-1: 'Not available',
     1: 'Fine weather',
     2: 'Raining',
     3: 'Windy',
     4: 'Snowing',
     5: 'Heavy rain',
     6: 'Heavy rain & wind',
     7: 'Heavy snow',
     8: 'Fog or mist',
     9: 'Other'
}

# Apply mapping directly to the column
collision['weather_conditions'] = collision['weather_conditions'].map(weather_map)


print(f'weather_conditions = ',collision['weather_conditions'].unique())

"""Data cleaning - Vehicle Dataset"""

#To check attributes with negative values
numeric_cols = vehicle.select_dtypes(include=['number'])
cols_with_neg_values = numeric_cols.columns[(numeric_cols < 0).any()]
print(f'cols_with_neg_values = {(cols_with_neg_values)}')

#Check the number of negative values present in the numeric columns of the dataset
vehicle_neg_value = (numeric_cols < 0).sum()
print(f'Negative values in the numeric fields of the vehicle DataFrame:\n{vehicle_neg_value}')

#Filtering out the negative values of columns sex_of_driver, age_of_driver, engine_capacity_cc, age_of_vehicle
#Find the percentage of negative values present in sex_of_driver
unidentified_sex_percentage = (vehicle['sex_of_driver'] <= 0 ).sum() / len(vehicle)*100
print(f"Percentage of unidentified sex of drivers = {unidentified_sex_percentage:.1f}%")

#Proceed to drop the negative values of speed limit
cleaned_sex_of_driver = vehicle[vehicle['sex_of_driver'] >= 0]

#Now proof check whether any negative values are present in speed limit attribute
cleaned_sex_of_driver = (cleaned_sex_of_driver['sex_of_driver'] < 0).sum()
print(f'cleaned_sex_of_driver = {(cleaned_sex_of_driver)}')

# Filtering the vehicles based on the age of vehicle (negate any negative values
# and filters only upto 40 years of the vehicle)
print(f"Min age: {vehicle['age_of_vehicle'].min()}")
print(f"Max age: {vehicle['age_of_vehicle'].max()}")
#Filter the age
filtered_age_of_vehicle = vehicle[(vehicle['age_of_vehicle'] >= 0) & (vehicle['age_of_vehicle']<=40)]

#Check the min max after filtering
print(f"Min age: {filtered_age_of_vehicle['age_of_vehicle'].min()}")
print(f"Max age: {filtered_age_of_vehicle['age_of_vehicle'].max()}")

#Check for the count of negative values available in the engine_capacity_cc
negative_val_engine_capacity = (vehicle['engine_capacity_cc'] < 0).sum()
print(f'negative_val_engine = ', negative_val_engine_capacity)

#Percentage
Percentage = (negative_val_engine_capacity/ len(vehicle)) * 100
print(f'Percentage of negative values = {Percentage}%')

#Since the percentage of negative values are more than 20% we shall replace the values with NaN rather than dropping them.
import numpy as np
vehicle['engine_capacity_cc'] = vehicle['engine_capacity_cc'].replace([-1, 0], np.nan)
print(f"Min engine_capacity: {vehicle['engine_capacity_cc'].min()}")
print(f"Max engine_capacity: {vehicle['engine_capacity_cc'].max()}")

#Filter the legal drivers in the vehicle dataset which are of age 17 - 70 from the age of drivers attribute
#Get the count of negative values first
negative_count = (vehicle['age_of_driver']<= 0).sum()
print(f'Negative count = ', negative_count)

#Percentage
Percentage = (negative_count/ len(vehicle)) * 100
print(f'Percentage of negative values = {Percentage}%')

# Since the percentage value is almost arounf 15% of the dataset we shall
# proceed to replace the values with NaN rather than dropping them
#First lets check the minimum and maximum values available so that the values can be filtered properly afterwards

print(f"Min age: {vehicle['age_of_driver'].min()}")
print(f"Max age: {vehicle['age_of_driver'].max()}")

#Replace the -1 values & 0 values with NaN
vehicle['age_of_driver'] = vehicle['age_of_driver'].replace([-1, 0], np.nan)
print(f"Min age: {vehicle['age_of_driver'].min()}")
print(f"Max age: {vehicle['age_of_driver'].max()}")

#Count of legal drivers
legal_drivers = ((vehicle['age_of_driver'] >= 17) & (vehicle['age_of_driver'] <= 70)).sum()
print(f'legal_drivers = {legal_drivers}')

#Filter the legal drivers
legal_drivers = vehicle[(vehicle['age_of_driver'] >= 17) & (vehicle['age_of_driver'] <= 70)]

#Check the Min max values as proof
print(f"Min age: {legal_drivers['age_of_driver'].min()}")
print(f"Max age: {legal_drivers['age_of_driver'].max()}")

"""Data Featuring
Aggregating by Vehicle Type
"""

# Group by 'vehicle_type' and count the occurrences
vehicle_type_counts = vehicle['vehicle_type'].value_counts().sort_index()
print("Vehicle Type Counts:\n", vehicle_type_counts)

"""Aggregating by Sex of Driver"""

# Group by 'sex_of_driver' and count the occurrences
sex_of_driver_counts = vehicle['sex_of_driver'].value_counts().sort_index()
print("Sex of Driver Counts:\n", sex_of_driver_counts)

"""Creating new attribute"""

# We can create one new attribute considering that most of the drivers are males
# High-risk: male drivers age 25 or younger
vehicle['high_risk_driver'] = ((vehicle['age_of_driver'] <= 40) & (vehicle['sex_of_driver'] == 1)).astype(int)

# Print count and percentage
count = vehicle['high_risk_driver'].sum()
percent = vehicle['high_risk_driver'].mean() * 100
print(f"High-risk drivers: {count} ({percent:.1f}%)")

"""CREATING DIMENSIONS & FACT TABLE"""

# Replace -1 in 'local_authority_district' with NaN in the collision DataFrame
collision['local_authority_district'] = collision['local_authority_district'].replace(-1, np.nan)

# Create the collision_details_dim
# Step 1: Select relevant columns from the original collision DataFrame, INCLUDING 'local_authority_district', and drop duplicates
collision_details_dim = collision[['local_authority_district', 'latitude', 'longitude', 'location_easting_osgr',
                                   'location_northing_osgr', 'collision_severity', 'weather_conditions']].drop_duplicates()

# Step 2: Add surrogate primary key
collision_details_dim['location_ID'] = collision_details_dim.reset_index(drop=True).index + 1

# Step 3: Reorder columns
collision_details_dim = collision_details_dim[['location_ID', 'local_authority_district', 'latitude', 'longitude',
                                               'location_easting_osgr', 'location_northing_osgr','weather_conditions']]
collision_details_dim.head()

#Create a dimension for casualty
#Create the primary key casualty ID by combining casualty reference & collision index together
casualty['Casualty_ID'] = casualty['casualty_reference'].astype(str) + '-' + casualty['collision_index'].astype(str)

#Build the dimension table
casualty_dim = casualty[['Casualty_ID','age_of_casualty','sex_of_casualty','casualty_type','casualty_severity']].drop_duplicates()
casualty_dim.head()

#Create a dimension for vehicle
#Create the primary key vehicle ID by combining vehicle reference & collision index together
vehicle['Vehicle_ID'] = vehicle['vehicle_reference'].astype(str) + '-' + vehicle['collision_index'].astype(str)

#Build the dimension table
vehicle_dim = vehicle[['Vehicle_ID','vehicle_type','age_of_vehicle','engine_capacity_cc','age_of_driver']].drop_duplicates()
vehicle_dim.head()

#Create a dimension for time from the collision dataset
#Create the primary key Time_ID by combining date & collision index
collision['Time_ID'] = collision['date'].astype(str) + '-' + collision['collision_index'].astype(str)

collision['day_of_week'].unique()
day_of_week_map = {1:"Monday",
2 : "Tuesday",
3 : "Wednesday",
4 : "Thursday",
5 : "Friday",
6 : "Saturday",
7 : "Sunday"
}


#Build the dimension table
collision['day_of_week'] = collision['day_of_week'].map(day_of_week_map)
time_dim = collision[['Time_ID','date','day_of_week','time']].drop_duplicates()
time_dim.head()

"""The fact table is created centering collision. Collisions are the main reason why the casualties exist and also why the vehicles are checked as well"""

# Define the columns that uniquely identify a 'location' in collision_details_dim.
location_identifying_cols = [
    'local_authority_district', 'latitude', 'longitude',
    'location_easting_osgr', 'location_northing_osgr'
]

# Create the fact table by chaining merge operations to bring in all necessary IDs and measures.
# Start with the collision data, which contains collision_index, Time_ID, and measures.
fact_table = (
    collision
    .merge(
        collision_details_dim[location_identifying_cols + ['location_ID']],
        on=location_identifying_cols,
        how='left'
    )
    .merge(
        casualty[['collision_index', 'casualty_reference', 'Casualty_ID']],
        on='collision_index', # Merge casualty information based on collision_index
        how='left'
    )
    .merge(
        vehicle[['collision_index', 'vehicle_reference', 'Vehicle_ID']],
        on='collision_index', # Merge vehicle information based on collision_index
        how='left'
    )
    # Select the final columns for the fact table
    [['collision_index', 'location_ID', 'Casualty_ID', 'Vehicle_ID', 'Time_ID',
      'number_of_vehicles', 'number_of_casualties', 'collision_severity']]
)

# Display the head of the fact table to verify
fact_table.head()

"""Connect the dimension models & fact table to SQLite Database to store in the data"""

#Create the connection to SQLite database
import sqlite3
conn = sqlite3.connect('UK Road Safety analysis.db')

#Load the dimension and fact tables to seperate tables in the Database
collision_details_dim.to_sql('collision_details_dim', conn, if_exists='replace', index=False)
casualty_dim.to_sql('casualty_dim', conn, if_exists='replace', index=False),
vehicle_dim.to_sql('vehicle_dim', conn, if_exists='replace', index=False),
time_dim.to_sql('time_dim', conn, if_exists='replace', index=False)

#Load the fact table
fact_table.to_sql('fact_table', conn, if_exists='replace', index=False)

# Read data from a dimension table to proof check
dim_query = "SELECT * FROM collision_details_dim LIMIT 5;"
dim_df = pd.read_sql_query(dim_query, conn)
display(dim_df.head())

# Read data from the fact table to proof check
dim_query = "SELECT * FROM fact_table LIMIT 5;"
dim_df = pd.read_sql_query(dim_query, conn)
display(dim_df.head())

#Close the connection to the SQLite database.
import sqlite3
conn = sqlite3.connect('UK Road Safety analysis.db')